checkbox_map = {
    "1": "Head",
    "2": "Abdomen",
    "3": "Elbow",
    "4": "Hip",
    "5": "Lower leg (incl. Achilles tendon)",
    "6": "Neck",
    "7": "Lumbosacral",
    "8": "Forearm",
    "9": "Groin",
    "10": "Ankle",
    "11": "Chest",
    "12": "Shoulder",
    "13": "Wrist",
    "14": "Thigh",
    "15": "Foot",
    "16": "Thoracic spine",
    "17": "Upper arm",
    "18": "Hand",
    "19": "Knee",
    "20": "Right",
    "21": "Left",
    "22": "Bilateral/central",
    "23": "Concussion",
    "24": "Meniscus lesion",
    "25": "Haematoma/contusion/bruise (incl. compartment syndrome)",
    "26": "Fracture (specify if stress fracture)",
    "27": "Cartilage lesion",
    "28": "Nerve injury (central or peripheral other than concussion)",
    "29": "Other bone injury (e.g., bone stress)",
    "30": "Muscle rupture/tear/strain**",
    "31": "Dental injury*",
    "32": "Joint dislocation/subluxation*",
    "33": "Tendon rupture/tendinopathy",
    "34": "Vessel injury (excl. skin haematoma)",
    "35": "Joint sprain (i.e., ligament/capsule)",
    "36": "Abrasion",
    "37": "Bursitis",
    "38": "Arthritis/synovitis/capsulitis",
    "39": "Laceration",
    "40": "Overuse unspecified",
    "41": "Other injury (please specify):",
    "42": "Training",
    "43": "Match (min. of injury)",
    "44": "N/A (gradual onset injury)",
    "45": "Football training",
    "46": "Football & other training",
    "47": "League match",
    "48": "Friendly match",
    "49": "Other training",
    "50": "Reserve/youth team training",
    "51": "Champions League",
    "52": "Reserve/youth team match",
    "53": "National team",
    "54": "Other cup match",
    "55": "Overuse (repetitive mechanism)",
    "56": "Trauma (acute mechanism)",
    "57": "Gradual onset",
    "58": "Sudden onset",
    "59": "No",
    "60": "Yes, direct contact (to injured body part)",
    "61": "Yes, indirect contact (to other body part)",
    "62": "Running/sprinting",
    "63": "Heading",
    "64": "Controlling the ball",
    "65": "Tackling other player",
    "66": "Blocked*",
    "67": "Twisting/turning",
    "68": "Landing (incl. jumping)",
    "69": "Hit by ball",
    "70": "Tackled by other player",
    "71": "Use of arm/elbow*",
    "72": "Shooting/passing",
    "73": "Falling (incl. diving)",
    "74": "Collision",
    "75": "Sliding/stretching*",
    "76": "Other player action",
    "77": "No",
    "78": "Yes (give date of return from previous injury)",
    "79": "No foul",
    "80": "Opponent foul",
    "81": "Own foul",
    "82": "Yellow card",
    "83": "Red card",
    "84": "Clinical only",
    "85": "X-ray",
    "86": "Ultrasonography",
    "87": "MRI",
    "88": "Other (specify)",
    "89": "No",
    "90": "Yes",
    "91": "No",
    "92": "Yes",
    "93": "No",
    "94": "Yes (specify)",
    "95": "No",
    "96": "Yes (specify)",
}
